name: Check Secrets

on:
  push:
    branches:
        - main
jobs:
  hit_endpoint_job:
    runs-on: ubuntu-latest  

    steps:
    - name: Check secrets
      run: |
        echo ${{ secrets.URL_ODOO }} echo ${{ vars.URL_ODOO }}
