name: Check Secrets

on:
  push:
    branches:
        - main
jobs:
  hit_endpoint_job:
    runs-on: ubuntu-latest  
    
    environment:
      name: tes-satu

    steps:
    - name: Check secrets
      run: |
        curl -X POST -H "Content-Type: application/json" -d '{"username": "${{secrets.USERNAME}}", "password": "${{sercets.PASSWORD}}"}' https://dbca-103-183-250-30.ngrok-free.app/api/auth/get_tokens                                  
        echo '${{ secrets.USERNAME }}' echo ${{ vars.URL_ODOO }}
