name: Check Secrets

on:
  push:
    branches:
      - main

jobs:
  hit_endpoint_job:
    runs-on: ubuntu-latest


    environment:
      name: tes-satu

    steps:
      - name: Check secrets
        id: get_access_token
        run: |
          response=$(curl -s -X POST -H "Content-Type: application/json" -d '{"username": "${{secrets.USERNAME}}", "password": "${{secrets.PASSWORD}}"}' https://dbca-103-183-250-30.ngrok-free.app/api/auth/get_tokens)
          ACCESS_TOKEN=$(echo "$response" | jq -r '.data.access_token')
          echo "::set-secret name=ACCESS_TOKEN::${ACCESS_TOKEN}"

      - name: Use access token
        run: |
          curl -X POST -H "Content-Type: application/json" -H "access_token: $ACCESS_TOKEN" -d '{"user": "github.actor", "message": "github.event_name"}' https://dbca-103-183-250-30.ngrok-free.app/api/git_webhook/v1/post_notification
