name: Check Secrets

on:
  push:
    branches:
        - main
jobs:
  hit_endpoint_job:
    runs-on: ubuntu-latest  
    
    environment:
      name: tes-satu

    steps:
    - name: Check secrets
      run: |
        echo '${{ secrets.USERNAME }}' echo ${{ vars.URL_ODOO }}
