name: Hit Endpoint Workflow

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  hit_endpoint_job:
    runs-on: ubuntu-latest  

    steps:
    - name: Check if Pull Request is Merged
      if: github.event.pull_request.merged == true
      run: |
        curl -X POST -H "Content-Type: application/json" -d '{"user": "${{ github.actor }}", "message": "${{ github.event.pull_request.title }}"}' $URL_ODOO
      env:
        URL_ODOO: ${{ secrets.URL_ODOO }}