name: Hit Endpoint Workflow
on:
  push:
    branches:
      - master  # Change this to your branch name if needed

jobs:
  hit_endpoint_job:
    runs-on: ubuntu-latest  # You can change the operating system if needed

    steps:
    - name: Hit Endpoint
      run: |
        curl -X POST -H "Content-Type: application/json" -d '{"user": github.actor, "message": github.event_name}' https://efb3-103-183-250-30.ngrok-free.app/api/git_webhook/v1/post_notification
