name: Hit Endpoint Workflow

on:
  pull_request:
    types: [closed]
    branches:
      - master
env:
  # Setting an environment variable with the value of a configuration variable
  URL_ODOO: ${{ vars.URL_ODOO }}

jobs:
  hit_endpoint_job:
    runs-on: ubuntu-latest  

    environment:
      name: tes-satu

    steps:
    - name: Check if Pull Request is Merged
      if: github.event.pull_request.merged == true
      run: |
        curl -X POST -H "Content-Type: application/json" -d '{"user": "${{ github.actor }}", "message": "${{ github.event.pull_request.title }}"}' ${{ vars.URL_ODOO }}
