name: Hit Endpoint Workflow
on:
  push:
    branches:
      - master  

jobs:
  hit_endpoint_job:
    runs-on: ubuntu-latest  

    steps:
    - name: Hit Endpoint
      run: |
        curl -X POST -H "Content-Type: application/json" -d '{"user": "github.actor", "message": "github.event_name"}' https://efb3-103-183-250-30.ngrok-free.app/api/git_webhook/v1/post_notification
